FROM clavator-create-os-images

RUN git clone --bare https://github.com/mabels/clavator.git /clavator.git
RUN git clone --bare https://github.com/mabels/gnupg.git -b quick-keytocard /gnupg.git
RUN git clone --bare https://aur.archlinux.org/gnupg-clavator.git  /gnupg-clavator.git

#COPY mirrorlist /etc/pacman.d/
COPY makepkg.patch /

CMD ["/bin/bash"]

